// <auto-generated />
using System;
using Dodorassik.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dodorassik.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502140000_AddSubscriptionTier")]
    partial class AddSubscriptionTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.HasPostgresExtension("vector");

            modelBuilder.Entity("Dodorassik.Core.Domain.Assistant.GameMechanic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeMax").HasColumnType("integer");
                    b.Property<int>("AgeMin").HasColumnType("integer");
                    b.Property<int?>("DurationMinutes").HasColumnType("integer");
                    b.Property<float[]>("Embedding").HasColumnType("vector(1536)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string[]>("Mechanics").IsRequired().HasColumnType("text[]");
                    b.Property<int?>("PlayerCountMax").HasColumnType("integer");
                    b.Property<int?>("PlayerCountMin").HasColumnType("integer");

                    b.Property<string>("SourceGame")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string[]>("Themes").IsRequired().HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");
                    b.HasIndex("Format");
                    b.ToTable("GameMechanics");
                });

            modelBuilder.Entity("Dodorassik.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<Guid>("Id"));

                    b.Property<int>("AiGenerationsUsed").HasColumnType("integer");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("FamilyId").HasColumnType("uuid");
                    b.Property<DateTime?>("LastLoginUtc").HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Role").HasColumnType("integer");
                    b.Property<int>("Tier").HasColumnType("integer");

                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("FamilyId");
                    b.ToTable("Users");
                });

            // (other entity definitions omitted for brevity — not used by migration runner)
#pragma warning restore 612, 618
        }
    }
}
